blogs/urls.py
from django.conf.urls import patterns,url
from blogs import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
	url(r'^(?P<blog_id>\d+)/view/$',views.view,name='view'),
)

django_tut/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings


#TASTYPIE APIS
from photographs.api import PhotographImageResource
from portfolios.api import ProjectResource , ProjectImageResource
from blogs.api import ArticleResource

photographimage_resource = PhotographImageResource()
project_resource = ProjectResource()
projectImage_resource = ProjectImageResource()
article_resource = ArticleResource()

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'django_tut.views.home', name='home'),
    # url(r'^django_tut/', include('django_tut.foo.urls')),
    url(r'^$','portfolios.views.index',name="home"),
    url(r'^photographs/',include('photographs.urls',namespace="photographs")),
    url(r'^projects/',include('portfolios.urls',namespace="projects")),
    url(r'^blogs/',include('blogs.urls',namespace="blogs")),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^manage/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^manage/', include(admin.site.urls)),
    url(r'^api/', include(project_resource.urls)),
    url(r'^api/', include(projectImage_resource.urls)),
    url(r'^api/', include(photographimage_resource.urls)),
    url(r'^api/', include(article_resource.urls)),
)

if settings.DEBUG:
	urlpatterns += staticfiles_urlpatterns()

photographs/urls.py
from django.conf.urls import patterns,url
from photographs import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
	url(r'^(?P<image_id>\d+)/view/$',views.view,name='view')
)

portfolios/urls.py
from django.conf.urls import patterns, url
from portfolios import views

urlpatterns = patterns('',
	url(r'^$',views.work,name='work'),
)

.south.bak/models.py
from django.db import models
from south.db import DEFAULT_DB_ALIAS

class MigrationHistory(models.Model):
    app_name = models.CharField(max_length=255)
    migration = models.CharField(max_length=255)
    applied = models.DateTimeField(blank=True)

    @classmethod
    def for_migration(cls, migration, database):
        try:
            # Switch on multi-db-ness
            if database != DEFAULT_DB_ALIAS:
                # Django 1.2
                objects = cls.objects.using(database)
            else:
                # Django <= 1.1
                objects = cls.objects
            return objects.get(
                app_name=migration.app_label(),
                migration=migration.name(),
            )
        except cls.DoesNotExist:
            return cls(
                app_name=migration.app_label(),
                migration=migration.name(),
            )

    def get_migrations(self):
        from south.migration.base import Migrations
        return Migrations(self.app_name)

    def get_migration(self):
        return self.get_migrations().migration(self.migration)
    
    def __unicode__(self):
        return "<%s: %s>" % (self.app_name, self.migration)

blogs/models.py
from django.db import models
from datetime import datetime, date, time
from django.db.models import signals
import django_tut.settings as settings
import twitter

def tweet_to_account(sender,instance,created,**kwargs):
	if(created):
		api = twitter.Twitter(
			auth=twitter.OAuth( '156908431-RleGgAQssuDv8vgwK9Gv43tWAQKxJBg1ZOpVPPo',
						'E2tFbNSIbToJcwmK27Ax5jhOQUzfcnarUEmypaZtQ',
						'5fLRBbVCR2WGCwxttHXAhA',
						'mPWJDidNBJfDG7J0rfJUOomKBY8XL79SFTjDMGHjAU'
			)
		)
		tweet = 'BLOG: '+instance.title+'. '+settings.DJANGO_DOMAIN_NAME+'blogs/'+str(instance.id)+'/view/'
		api.statuses.update(status=tweet)

class Tag(models.Model):
	name = models.CharField(max_length=200)
	created = models.DateTimeField(default=datetime.now(),blank=True);	


	def __unicode__(self):
		return self.name

class Article(models.Model):
	tags = models.ManyToManyField(Tag,blank=True)
	title = models.CharField(max_length=400)
	content = models.TextField()
	created = models.DateTimeField(default=datetime.now(),blank=True);
	script = models.FileField(upload_to="media/blogs/",blank=True)
	stylesheet = models.FileField(upload_to="media/blogs",blank=True)
	like = models.IntegerField(default=0)

	def __unicode__(self):
		return self.title


class Comment(models.Model):
	comment = models.CharField(max_length=10000)
	created = models.DateTimeField(default=datetime.now(),blank=True);

	def __unicode__(self):
		return self.comment

signals.post_save.connect(tweet_to_account,sender=Article)

photographs/models.py
from django.db import models
from datetime import datetime, date,time

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()

	def __unicode__(self):
		return self.name

class PhotographImage(models.Model):
	category = models.ForeignKey(Category,related_name="photographImages")
	name = models.CharField(max_length=200)
	description = models.TextField()
	image_s = models.CharField(max_length=200,null=True,blank=True)
	image_m = models.CharField(max_length=200,null=True,blank=True)
	image_l = models.CharField(max_length=200,null=True,blank=True)
	likes = models.IntegerField(default=0)
	uploaded = models.DateTimeField(default=datetime.now(),blank=True)
	star = models.NullBooleanField()

	def __unicode__(self):
		return self.name

	def save(self,*args,**kwargs):
		# USING PICASA CDN - IF SIZE 144PX IS DETECTED, SAVE AS 320PX AND PROPAGATE TO OTHER SIZES
		image_link = self.image_s.rsplit('/s144/')
		if len(image_link) > 1:
			self.image_s = image_link[0] +  '/s320/' + image_link[1]
			self.image_m = image_link[0] +  '/s1000/' + image_link[1]
			self.image_l = image_link[0] +  '/s0/' + image_link[1]

		super(PhotographImage,self).save(*args,**kwargs)

portfolios/models.py
from django.db import models

class Technology(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField(blank=True)
	
	def __unicode__(self):
		return self.name

class Project(models.Model):
	name = models.CharField(max_length=200)
	url = models.CharField(blank=True, max_length=200)
	description = models.TextField(blank=True)
	technologies = models.ManyToManyField(Technology)

	def __unicode__(self):
		return self.name


class ProjectImage(models.Model):
	project = models.ForeignKey(Project,related_name='projectImages')
	name = models.CharField(max_length=200,default='-')
	url = models.ImageField(upload_to="media/images/projects/",max_length=200,null=True)

	def __unicode__(self):
		return self.name

blogs/views.py
from django.shortcuts import render
from django.template import Context, loader
from django.http import HttpResponse
from blogs.models import *
import twitter

def index(request):
	return render(request,'blogs/index.html')

def view(request,blog_id):
	blog = Article.objects.select_related().get(id=blog_id)
	print blog.created
	context = Context({
		'blog':blog,
	})
	return render(request,'blogs/view.html',context)

photographs/views.py
# Create your views here.
from django.http import HttpResponse
#either this
from django.template import Context, loader

#or this
from django.shortcuts import render

#import models
from photographs.models import *

def index(request):
	# template = loader.get_template('photographs/index.html')
	# image_list = PhotographImage.objects.order_by('-uploaded')
	# context  = Context({
	# 	'image_list': image_list,
	# })
	return render(request,'photographs/index.html')

def view(request,image_id):
	image = PhotographImage.objects.order_by('-uploaded')[:5]
	context = Context({
		'image_list': image,
	})
	return render(request,'photographs/index.html',context)

portfolios/views.py
from django.shortcuts import render
from django.conf import settings
#import PHOTOGRAPHS IS FOR GALLERY
from portfolios.models import *
from photographs.models import PhotographImage
import os


def index(request):
	image_list = PhotographImage.objects.order_by('-uploaded')[:5]
	context = {
		'home_active':'active',
		'image_list':image_list
	}
	return render(request,'portfolios/index.html',context)

def work(request):
	return render(request,'portfolios/work.html')

static-root/grappelli/tinymce/examples/templates/layout1.htm
<table border="1">
	<thead>
		<tr>
			<td>Column 1</td>
			<td>Column 2</td>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>Username: {$username}</td>
			<td>Staffid: {$staffid}</td>
		</tr>
	</tbody>
</table>

static-root/grappelli/tinymce/examples/templates/snippet1.htm
This is just some <strong>code</strong>.

templates/.admin.bak/actions.html
{% load i18n %}
<div class="actions">
    {% for field in action_form %}{% if field.label %}<label>{{ field.label }} {% endif %}{{ field }}{% if field.label %}</label>{% endif %}{% endfor %}
    <button type="submit" class="button" title="{% trans "Run the selected action" %}" name="index" value="{{ action_index|default:0 }}">{% trans "Go" %}</button>
    {% if actions_selection_counter %}
        <script type="text/javascript">var _actions_icnt="{{ cl.result_list|length|default:"0" }}";</script>
        <span class="action-counter">{{ selection_note }}</span>
        {% if cl.result_count != cl.result_list|length %}
        <span class="all">{{ selection_note_all }}</span>
        <span class="question">
            <a href="javascript:;" title="{% trans "Click here to select the objects across all pages" %}">{% blocktrans with cl.result_count as total_count %}Select all {{ total_count }} {{ module_name }}{% endblocktrans %}</a>
        </span>
        <span class="clear"><a href="javascript:;">{% trans "Clear selection" %}</a></span>
        {% endif %}
    {% endif %}
</div>

templates/.admin.bak/app_index.html
{% extends "admin/index.html" %}
{% load i18n %}
{% load url from future %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo;
{% for app in app_list %}
{% blocktrans with app.name as name %}{{ name }}{% endblocktrans %}
{% endfor %}
</div>
{% endblock %}
{% endif %}

{% block sidebar %}{% endblock %}

templates/.admin.bak/base.html
{% load admin_static %}{% load url from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active and user.is_staff %}
        <div id="user-tools">
            {% trans 'Welcome,' %}
            <strong>{% filter force_escape %}{% firstof user.first_name user.username %}{% endfilter %}</strong>.
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

templates/.admin.bak/base_site.html
{% extends "admin/base.html" %}
{% load i18n %}

{% block title %}{{ title }} | {% trans 'Django site admin' %}{% endblock %}

{% block branding %}
<h1 id="site-name">{% trans 'Mysterious Dev Blog' %}</h1>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/.admin.bak/change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_modify %}
{% load url from future %}
{% load admin_urls %}

{% block extrahead %}{{ block.super }}
{% url 'admin:jsi18n' as jsi18nurl %}
<script type="text/javascript" src="{{ jsi18nurl|default:"../../../jsi18n/" }}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}

{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ app_label|capfirst|escape }}</a>
&rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% trans 'Add' %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li><a href="history/" class="historylink">{% trans "History" %}</a></li>
    {% if has_absolute_url %}<li><a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif%}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.module_name }}_form">{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% blocktrans count counter=errors|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% if adminform and add %}
   <script type="text/javascript">document.getElementById("{{ adminform.first_field.id_for_label }}").focus();</script>
{% endif %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}

templates/.admin.bak/change_list.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list %}
{% load url from future %}
{% load admin_urls %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />
  {% if cl.formset %}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
  {% endif %}
  {% if cl.formset or action_form %}
    {% url 'admin:jsi18n' as jsi18nurl %}
    <script type="text/javascript" src="{{ jsi18nurl|default:'../../jsi18n/' }}"></script>
  {% endif %}
  {{ media.css }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% block extrahead %}
{{ block.super }}
{{ media.js }}
{% if action_form %}{% if actions_on_top or actions_on_bottom %}
<script type="text/javascript">
(function($) {
    $(document).ready(function($) {
        $("tr input.action-select").actions();
    });
})(django.jQuery);
</script>
{% endif %}{% endif %}
{% endblock %}

{% block bodyclass %}change-list{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=cl.opts.app_label %}">{{ app_label|capfirst|escape }}</a>
&rsaquo; {{ cl.opts.verbose_name_plural|capfirst }}
</div>
{% endblock %}
{% endif %}

{% block coltype %}flex{% endblock %}

{% block content %}
  <div id="content-main">
    {% block object-tools %}
      {% if has_add_permission %}
        <ul class="object-tools">
          {% block object-tools-items %}
            <li>
              <a href="{% url cl.opts|admin_urlname:'add' %}{% if is_popup %}?_popup=1{% endif %}" class="addlink">
                {% blocktrans with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktrans %}
              </a>
            </li>
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}
    {% if cl.formset.errors %}
        <p class="errornote">
        {% blocktrans count cl.formset.errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
        </p>
        {{ cl.formset.non_form_errors }}
    {% endif %}
    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
      {% block search %}{% search_form cl %}{% endblock %}
      {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

      {% block filters %}
        {% if cl.has_filters %}
          <div id="changelist-filter">
            <h2>{% trans 'Filter' %}</h2>
            {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
          </div>
        {% endif %}
      {% endblock %}

      <form id="changelist-form" action="" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %}>{% csrf_token %}
      {% if cl.formset %}
        <div>{{ cl.formset.management_form }}</div>
      {% endif %}

      {% block result_list %}
          {% if action_form and actions_on_top and cl.full_result_count %}{% admin_actions %}{% endif %}
          {% result_list cl %}
          {% if action_form and actions_on_bottom and cl.full_result_count %}{% admin_actions %}{% endif %}
      {% endblock %}
      {% block pagination %}{% pagination cl %}{% endblock %}
      </form>
    </div>
  </div>
{% endblock %}

templates/.admin.bak/filter.html
{% load i18n %}
<h3>{% blocktrans with filter_title=title %} By {{ filter_title }} {% endblocktrans %}</h3>
<ul>
{% for choice in choices %}
    <li{% if choice.selected %} class="selected"{% endif %}>
    <a href="{{ choice.query_string|iriencode }}">{{ choice.display }}</a></li>
{% endfor %}
</ul>

templates/.admin.bak/invalid_setup.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% load url from future %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {{ title }}
</div>
{% endblock %}

{% block content %}
<p>{% trans "Something's wrong with your database installation. Make sure the appropriate database tables have been created, and make sure the database is readable by the appropriate user." %}</p>
{% endblock %}

templates/common/navigation.html
{% load url from future %}
<div class="top-bar home-border master-bg">
  <div class="attached">
    <div class="name">
      <span>
      {# <img src="{{MEDIA_URL}}layout/cz.png"/> #}
    </span>
    </div>
    <ul class="right">
      <li><a href="{% url 'home' %}" class="master-hover"><p class="social foundicon-torso "> ME</p></a></li>
      <li><a href="{% url 'blogs:index' %}" class="master-hover"><p class="social foundicon-wordpress "> blog</p></a></li>
      <li><a href="{% url 'projects:work' %}" class="master-hover"><p class="general foundicon-edit "> projects</p></a></li>
      <li><a href="{% url 'photographs:index' %}" class="master-hover"><p class="social foundicon-instagram "> photos</p></a></li>
      {# <li><a href="{% url 'contact' %}"><p class="general foundicon-phone "> contact</p></a></li> #}
    </ul>
  </div>
</div>

templates/portfolios/index.html
{% extends "common/layout.html" %}
{% load url from future %}
{# CSS HERE #}
{% block css %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/portfolios_index.css">
{% endblock css %}

{# JAVASCRIPT HERE #}
{% block javascript %}
	<script type="text/javascript" src="{{ STATIC_URL }}js/portfolios_index.js"></script>
{% endblock javascript %}


{% block main_content %}
<div class="row display">
	<div class="three columns">
	<img src="{{ MEDIA_URL }}portfolios_index/profile.jpg" id="profile_image"/>
	</div>
	<div class="nine columns">
		<div class="row top_selector">
			<dl class="tabs three-up">
				<dd selector_data="i_am"><a href="#"><h3 id="first_selector" class="slave-invert-hover">I AM </h3></a></dd>
				<dd selector_data="i_do"><a href="#"><h3 class="slave-invert-hover">I CODE</h3></a></dd>
				<dd selector_data="i_love"><a href="#"><h3 class="slave-invert-hover">I LOVE</h3></a></dd>
			</dl>
		</div>
		<div class="row top_content">
			<p> 
				code style work 
				<span class="i_am">David Tjokroaminoto</span>
				<span class="i_love">backend developing</span>
				food paragraph cascading
				<span class="i_do">CSS3</span> 
				hypertext markup language
				<span class="i_do">Javascript</span>
				color border android
				<span class="i_love">computers</span>
				<span class="i_am">student</span>
				padding boilerplate angular
				<span class="i_do">Django</span>
				<span class="i_love">cats</span>
				yeoman node array object 
				<span class="i_am">geek</span>
				<span class="i_love">programming</span>
				<span class="i_do">HTML5</span>
				textbox color ipad precision
				<span class="i_love">designing websites</span> 
				<span class="i_am">aspiring developer</span>
				background sublime text macbook windows 
				<span class="i_do">PHP</span> 
				linux redhat iphone wordpress backbone tablet
				<span class="i_love">photography</span>
				<span class="i_do">Python</span>
				<span class="i_am">Melbourne, Australia</span>
			</p>
		</div>
	</div>
</div>
<div class="row">
	<div class="twelve columns">
		<dl class="tabs twelve-up"><dd class="active grey-border"><a href="#" class="slave">About Me</a></dd></dl>
		<ul class="tabs-content contained">
			<li class="active">
				<p class="newscycle">
					David Tjokroaminoto (cho-co-ah-me-no-tow)<br>
					Self-proclaimed geek.<br>
					Student at Monash University.<br>
					Loves web development.<br>
					Obsessive about building clean-looking websites.<br>
					Dwells in Melbourne, Australia.
				</p>
			</li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="twelve columns">
		<dl class="tabs twelve-up"><dd class="active grey-border"><a href="#" class="slave">Origin</a></dd></dl>
		<ul class="tabs-content contained">
			<li class="active">
				<div class="row">
					<div class="four columns">
						<p>
							from <span id="id_flag">Medan, Indonesia</span><br>
							to <span id="au_flag">Melbourne, Australia</span><br><br>
							There are many things i like about Melbourne, one of them is the ridiculously comfortable weather :)
						</p>
							<h4><small class="right">*beware of sharks!</small></h4>
					</div>
					<div class="eight columns">
						<img src="{{ MEDIA_URL }}portfolios_index/origin.jpg" class="shadow">
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="twelve columns">
		<dl class="tabs twelve-up"><dd class="active grey-border"><a href="#" class="slave">Anatomy</a></dd></dl>
		<ul class="tabs-content contained">
			<li class="active">
				<div class="row">
					<div class="four columns">
						<p>
							I devour emerging website technologies, latest markup language, scripting language, frameworks.<br>
							Basically anything that can level up my skills in developing beautiful websites.
						</p>
					</div>
					<div class="eight columns">
						<img src="{{ MEDIA_URL }}portfolios_index/devour.png">
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="row">
	<div class="twelve columns">
		<dl class="tabs twelve-up"><dd class="active grey-border"><a href="#" class="slave">Photography</a></dd></dl>
		<ul class="tabs-content contained">
			<li class="active">
				<div class="row display">
					<div class="twelve columns centered">
						<div id="orbit_featured">
						{% for image in image_list %}
							<img src="{{ image.image_m }}"/>
						{% endfor %}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="twelve columns ">
						<a href="{% url 'photographs:index' %}" class="button secondary comfortaa slave slave-hover grey-border right">GALLERY ></a>
					</div>
				</div>
			</li>
		</ul>
	</div>
</div>
{% endblock main_content %}